### ISSUE TITLE
Rename this repository to ocsipersist-legacy

### ISSUE THREAD

**Issue by jrochel** [ocsigen/ocsipersist-legacy#6]
I am currently working on a refurbished version of this project: https://github.com/jrochel/ocsipersist
It works pretty well and I think we can consider this repository outdated.
If one of the admins renames this project I can move my version (after some cleaning up) to the ocsigen account.
@vasilisp @Drup @balat

**Comment by jrochel** [comment]
If this is not desired, I can obviously make a PR (albeit an ugly one).

**Comment by jrochel** [comment]
Hmm, I'm tending to the latter actually. Create some continuity between the two incarnations.

**Comment by balat** [comment]
Done
